name: post entry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go install github.com/x-motemen/blogsync@latest

      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          blogsync push ./entry/2021/03/16/095021.md
        env:
          BLOGSYNC_PASSWORD: ${{ secrets.APIKEY }}
